#!/usr/bin/env osascript -l JavaScript

'use strict';

const cacheDuration =
  Number(
    $.NSProcessInfo.processInfo.environment.objectForKey('cache_duration').js
  ) || 3600;

const glApp = Application('GoodLinks');
glApp.includeStandardAdditions = true;

const items = glApp.links().map((link) => ({
  uid: link.id(),
  title: link.title(),
  subtitle: link.url(),
  arg: link.url(),
}));

const alfredItems = {
  cache: { seconds: cacheDuration, loosereload: true },
  items: items,
};

const alfredItemsJSON = JSON.stringify(alfredItems);

alfredItemsJSON;
